name: CI/CD pipeline
on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs: 
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 23.x ]
    
    steps: 
    - uses: actions/checkout@v4
      if: always()
    - name: Staring Node.js ${{ matrix.node-version }}
      if: always()
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install modules
      run: npm install
    - name: build project
      if: always()
      run: npm run build
    - name: linting
      if: always()
      run: npm run lint
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
    - name: Send message
      uses: aps-m/telegram-notify-action@v1
      with:
        token: ${{ secrets.TELEGRAM_TOKEN }}
        to: ${{ secrets.TELEGRAM_CHATID_TO }}
        message: |
          Успешный Деплой!
          Репозиторий: ${{ github.repository }}
          Коммит: ${{ github.sha }}
          Автор: ${{ github.actor }}
          Статус: Сборка и деплой завершены. Проект доступен на GitHub Pages.
    